### PR TITLE
Added scheduled snapshots

### PR DESCRIPTION
**Pull request by danquah**

### CODE REVIEW

**Comment by reload-branching-check** [comment]
**Reload Release Notes**

[See issues in Jira](https://reload.atlassian.net/issues/?jql=issuekey%20in%20())

**Comment by arnested** [comment]
LGTM :+1:

**Comment by reload-branching-check** [comment]
**Reload Release Notes**

[See issues in Jira](https://reload.atlassian.net/issues/?jql=issuekey%20in%20())

**Comment by reload-branching-check** [comment]
**Reload Release Notes**

[See issues in Jira](https://reload.atlassian.net/issues/?jql=issuekey%20in%20())

**Pull request merged**
