### PR TITLE
Linters using GH actions. RI-112

### PR DESCRIPTION
**Pull request by rasben**
Moving away from CodeClimate / Circle and using GH Actions to lint/check our code.

### CODE REVIEW

**Comment by rasben** [comment]
Who has access to remove LGTM, which is now replaced by github actions?

I assume it's here it needs to be removed, but I dont have rights.

https://github.com/reload/ddsdk2016/settings/installations

**Comment by rasben** [comment]
I fixed all the existing frontend issues, but there's 148 PHP issues that I dont really want to touch.
If someone else wants to fix them in the future, they're of course welcome to. :)

**Comment by arnested** [comment]
> Who has access to remove LGTM, which is now replaced by github actions?
> 
> I assume it's here it needs to be removed, but I dont have rights.
> 
> https://github.com/reload/ddsdk2016/settings/installations

I uninstalled it from our organization.

**Review by arnested — CHANGES_REQUESTED** [review]
Fra issuet:

> PHPStan: Same drill, installer mglaman/phpstan-drupal,
phpstan/phpstan-deprecation-rules og phpstan/phpstan-phpunit. Hvis
de allerede er installeret, så check lige at de ikke er pinned til en
0.x version (og hvis det er tilfældet, prøv at opgradere). 

phpstan & friends er i 0.x versioner i stedet for 1.x

> PHPStan kører ikke igennem reviewdog, for når den melder fejl, så er
det somregel en latent bug. Der kan være enkelte false positives
(oftest Drupalismer) man ikke har lyst til at fikse, dem kan man
tilføje til ignoreErrors. Level bør være mindst 5, gerne mere. Og hvis
det er helt galt og den sprøjter en uoverkommelig liste af fejl ud, så
kan man lave en [baseline](https://phpstan.org/user-guide/baseline).

Lige nu er den på level 1.

**Comment by rasben** [comment]
backstop-check approve

**Review by xendk — APPROVED** [review]
Looks good.. Anything in the stylelint configuration that would make sense to upstream to daft?

**Pull request merged**
