### PR TITLE
Added optional button styling to content-link - DDSDK-621

### PR DESCRIPTION
**Pull request by RoWaBo**
#### What does this PR do?
Added a checkbox to enable button styling on the content-link paragraph.

#### Where should the reviewer start?
Se den nye variation af content-link: https://pr-442-7oikaoy-55isd6w54kg6s.eu.platform.sh/artikel/logoer-0

#### What are the relevant tickets?
https://reload.atlassian.net/browse/DDSDK-621

### CODE REVIEW

**Review by blyme — APPROVED** [review]

**Comment by RoWaBo** [comment]
backstop-check approve

**Comment by RoWaBo** [comment]
backstop-check approve

**Comment by RoWaBo** [comment]
backstop-check approve

**Comment by RoWaBo** [comment]
backstop-check approve

**Comment by RoWaBo** [comment]
backstop-check approve

**Pull request merged**
