### PR TITLE
Update core. 9.4.8 => 9.5.9.

### PR DESCRIPTION
**Pull request by rasben**
```
composer require "drupal/core:^9" "drupal/core-composer-scaffold:^9" "drupal/core-project-message:^9" "drupal/core-recommended:^9" -W

composer require "drupal/core-dev:^9" --dev -W

drush updb -y

drush cex -y
```

### CODE REVIEW

**Comment by rasben** [comment]
Backstop is fucked. It reports errors that arent actually happening.

**Comment by rasben** [comment]
backstop-check approve

**Review by arnested — APPROVED** [review]
LGTM :+1:

**Comment by rasben** [comment]
backstop-check approve

**Pull request merged**
