### PR TITLE
Release 0.1.0 (Sprint 1)

### PR DESCRIPTION
**Pull request by danquah**

### CODE REVIEW

**Comment by reload-branching-check** [comment]
**Reload Release Notes**
- Topmenu
 https://reload.atlassian.net/browse/DDSDK-46

- Opsætning af Platform.sh
 https://reload.atlassian.net/browse/DDSDK-43

- Footer
 https://reload.atlassian.net/browse/DDSDK-48

- Artikel
 https://reload.atlassian.net/browse/DDSDK-19


[See issues in Jira](https://reload.atlassian.net/issues/?jql=issuekey%20in%20(DDSDK-46%2C+DDSDK-43%2C+DDSDK-48%2C+DDSDK-19))

**Comment by reload-branching-check** [comment]
**Reload Release Notes**
- Topmenu
 https://reload.atlassian.net/browse/DDSDK-46

- Opsætning af Platform.sh
 https://reload.atlassian.net/browse/DDSDK-43

- Footer
 https://reload.atlassian.net/browse/DDSDK-48

- Artikel
 https://reload.atlassian.net/browse/DDSDK-19


[See issues in Jira](https://reload.atlassian.net/issues/?jql=issuekey%20in%20(DDSDK-46%2C+DDSDK-43%2C+DDSDK-48%2C+DDSDK-19))

**Comment by mian3010** [comment]
Retest this please

**Comment by reload-branching-check** [comment]
**Reload Release Notes**
- Topmenu
 https://reload.atlassian.net/browse/DDSDK-46

- Opsætning af Platform.sh
 https://reload.atlassian.net/browse/DDSDK-43

- Footer
 https://reload.atlassian.net/browse/DDSDK-48

- Artikel
 https://reload.atlassian.net/browse/DDSDK-19


[See issues in Jira](https://reload.atlassian.net/issues/?jql=issuekey%20in%20(DDSDK-46%2C+DDSDK-43%2C+DDSDK-48%2C+DDSDK-19))

**Pull request merged**
